### ISSUE TITLE
auxpow working?

### ISSUE THREAD

**Issue by p3yot3** [bitcreditscc/uniqredit#1]
I notice this coin uses auxpow for merge mining - but I get this error:

"method not known"  when trying to implement it.

**Comment by p3yot3** [comment]
Is anyone active on this project?.......

**Comment by bitcreditscc** [comment]
Yes we are active. The auxpow has not yet been integrated.  If you know
how,  pull requests are welcome

**Comment by bitcreditscc** [comment]
Sorry for the late response btw,  we are migrating all uniqredit related
sources to a new account and organisation

**Comment by p3yot3** [comment]
Why would you include auxpow in your code if you don't know how to integrate it?

**Comment by p3yot3** [comment]
I'm sure miners will be pleased that you can't be bothered with your own project.

Good luck.

**Comment by bitcreditscc** [comment]
The mining reward is intentionally infetisimal, the transaction fees is
higher than the block reward so essentially   miners cannot send whatever
they mine.  Miners bore me.

**Comment by p3yot3** [comment]
The sole purpose of auxpow is **for** miners, there's no other use for it.

Uninstalled.

**Comment by bitcreditscc** [comment]
Uh. Yes, in our case miner who know they aren't getting paid.... How about
you look at get the specs first... maybe even the mission statement too
